name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  test:
    name: 'Test 🧪'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set the correct Node version using nvm
      shell: bash -l {0}
      run: nvm install

    - run: npm ci

    - run: npm run test:e2e:ci

    - if: always()
      run: docker-compose down

  dependabot:
    name: 'Dependabot 🤖'
    needs: [test]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: '${{ secrets.DEPENDABOT_TOKEN }}'

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.DEPENDABOT_TOKEN}}
