name: Continuous Integration

on:
  push:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write
  
jobs:
  test:
    name: 'Test 🧪'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set the correct Node version using nvm
      shell: bash -l {0}
      run: nvm install

    - run: npm ci

    - run: npm run test:e2e:ci

    - if: always()
      run: docker-compose down

  dependabot:
    name: 'Dependabot 🤖'
    needs: [test]
    runs-on: ubuntu-latest
    
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Approve and merge
        run: |
          gh pr edit "$PR_URL" --add-label "auto-merged"
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
