name: Node.js CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set the correct Node version using nvm
      shell: bash -l {0}
      run: nvm install

    - run: npm ci

    - run: npm run test:e2e:ci

    - if: always()
      run: docker-compose down
